### ISSUE TITLE
Fluxible-router suggestions for passport integration

### ISSUE THREAD

**Issue by drosko** [yahoo/flux-examples#122]
Does anyone have any suggestions on how to integrate passport policies into the fluxible-router example?  As in, to grab the req object to do req.logIn(), req.isAuthenticated, etc.

**Comment by christopherscott** [comment]
Good question; more generally, what would a good authentication scheme look like?

**Comment by jedireza** [comment]
Using a local passport strategy should be possible. I'd imagine you could create a login/auth service with `fluxible-plugin-fetchr` since `fetchr` services have access to `req`/`res`.

The following is just back-of-napkin code (it's not copy-pastable). I'm hoping it can help inspire you to find a solution.

__Setting up the local strategy:__
```js
passport.use(new LocalStrategy(
  function(username, password, done) {
    var conditions = { username: username };

    db.Users.findOne(conditions, function(err, user) {
      if (err) {
        return done(err);
      }

      if (!user) {
        return done(null, false, { message: 'Unknown user' });
      }

      bcryptProbably.validatePassword(password, user.password, function(err, isValid) {
        if (err) {
          return done(err);
        }

        if (!isValid) {
          return done(null, false, { message: 'Invalid password' });
        }

        return done(null, user);
      });
    });
  }
));
```

__Then inside your service, you can use the local strategy manually like this:__
```js
req._passport.instance.authenticate('local', function(err, user, info) {
  if (err) {
    return next(err);
  }

  if (!user) {
    // reply with "user not found or password mismatch"
  }
  else {
    req.login(user, function(err) {
      if (err) {
        return next(err);
      }

      // reply with "success"
    });
  }
})(req, res, next);
```

- - - - - - -

With 3rd-party/oauth strategies, the browser must hop through redirects. So you'll probably have to pop a window open so that happens in a different window so the page doesn't re-load.

**Comment by drosko** [comment]
Great thanks, I'll see what I can do with that approach.

**Comment by jamesjjk** [comment]
@redonkulus Hi, did you get anywhere with passport integration?

**Comment by redonkulus** [comment]
@jamesjjk nope, never looked into it.
