### ISSUE TITLE
client.js is huge

### ISSUE THREAD

**Issue by swese44** [yahoo/flux-examples#125]
These examples generate enormous webpack client.js files, up to 1.5MB. I understand this can be minified (393kb), and then gzipped (114kb), but are there any dependencies we can remove to cut the size down more? Thanks!

**Comment by mridgway** [comment]
So I looked through the fluxible-router example and the top 3 low-hanging fruit that could be addressed are the following dependencies:

 * async (in Fluxible for plugins) - Replace with promises and Promise.all?
 * events (in Fluxible for EventEmitter) - Replace with npm `eventemitter3`
 * util (in Fluxible for inherits) - Replace with npm `inherits`

If anyone wants to do a PR for these I will gladly accept. Those three contribute about 57kb unminified and ungzipped from what I found.

**Comment by mridgway** [comment]
Actually, I'm going to go ahead and PR the dispatchr ones.

**Comment by swese44** [comment]
Thanks Michale. removing debug might be another easy one

**Comment by cesarandreu** [comment]
-1 on removing debug.

**Comment by mridgway** [comment]
Debug is really useful in dev but not really in production since it's turned on at server start. We could consider wrapping the debug code with `if (process.env.NODE_ENV !== 'production')` which would allow dropping it entirely in webpack builds.

We also have a [strip-loader](https://github.com/yahoo/strip-loader) for webpack that will strip out calls to `debug` which you could use along with an `ignore` directive to remove the package entirely.

**Comment by swese44** [comment]
Oh nice, thanks

**Comment by rohit8** [comment]
+1 for cutting the size of dependencies

**Comment by mridgway** [comment]
All of the dependencies that I mentioned in https://github.com/yahoo/flux-examples/issues/125#issuecomment-83922507 have been removed or replaced with smaller packages. If we see other areas for improvement, let's create new issues for them individually.
