### ISSUE TITLE
Chat: why is the URL to the message fetchr service '/api/servicesmessage'?

### ISSUE THREAD

**Issue by ilkka** [yahoo/flux-examples#129]
I scratched my head for a while about this, getting "Fetcher could not be found" errors, but then realized that the name of the fetcher is apparently matched against whatever is left after taking out `/api/services`, and that includes the leading slash.

So, is this a bug or should service names actually include that leading slash, e.g.

```
module.exports = {
  name: '/message',
  ...
}
```

?

**Comment by Vijar** [comment]
Hi @ilkka 

So with our underlying `fetchr` library, your service name is integrated into the url like so `/api/services;message'. Notice the semicolon. You can read more about the semicolon and matrix params here: yahoo/fetchr#16

I am not sure why you're getting the "Fetcher could not be found" error though. Can you provide more details?

**Comment by Vijar** [comment]
Actually, I think I see your issue. This is indeed unexpected behavior. 

The way we match the service name is slightly ambiguous (https://github.com/yahoo/fetchr/blob/master/libs/fetcher.js#L80).

Basically both of these urls would be valid:
`/api/resource/message`
`/api/service/message`

Here is why:

Fetchr expects your url to be constructed like `/api/resource/message`, where `req.path` is `/resource/message`.
```
var path = req.path.substr(req.path.lastIndexOf('/resource/') + '/resource/'.length).split(';');
var path = req.path.substr(0 + 10).split(';');
var path = req.path.substr(10).split(';');
```
Which would make `path` evaluate to `message` as expected.

However if it can't find `resource` it will still proceed and calculate 'path'.
```
var path = req.path.substr(req.path.lastIndexOf('/resource/') + '/resource/'.length).split(';');
var path = req.path.substr(-1 + 10).split(';');
var path = req.path.substr(9).split(';');
```
In the case of `/api/service/message`, `req.path` will be `/service/message` and if we trim off 9 character from the begining, it will also evaluate to `message`.

This is an ambiguous case. I'm not sure this would be considered a bug though. Perhaps we can change the fetchr library to look for `/service/` rather than `/resource/` just to be consistent.

**Comment by ilkka** [comment]
Ahh okay, I see where I went wrong now. I basically assumed Fetchr mapped the service to an URL that matches the directory structure of the examples, i.e. 'serviceS'. A risk of trying to figure stuff out from just the example :) I did look through that code but somehow managed to miss the bits you quote.

Personally I feel like it'd be nice if I was able to (or perhaps even required to) specify the structure of the service URLs myself, much like I set the xhrPath when adding the plugin. That way it'd be unambiguous and under my control.

Thanks, this can be closed as far as I'm concerned :)
