### ISSUE TITLE
Routing issues when upgrading to Fluxible 0.5

### ISSUE THREAD

**Issue by rohit8** [yahoo/flux-examples#154]
I saw some inconsistent routing behavior when upgrading to Fluxible 0.5, where a route would render in an incomplete state. After some digging, my issue was resolved after I specified this in Application.jsx (which I saw being used in fluxible.io's github repo):
```
    shouldComponentUpdate(nextProps, nextState) {
        return nextProps.isNavigateComplete;
    }
```

Is this something that the Application components in the flux examples should have as well?

**Comment by mridgway** [comment]
This was a decision that we made to make navigation be optimistic, meaning it will show changes immediately rather than waiting for the `navigateAction` to complete. This improves user-perceived performance, but does mean that you should handle it correctly in your application. You may want to set a `loading` flag in your state somewhere to show a loading spinner, but I wouldn't recommend blocking any re-renders until the action has completed or the user may not know that anything is happening.
