### ISSUE TITLE
Use a more declarative router

### ISSUE THREAD

**Issue by benoneal** [yahoo/flux-examples#85]
Any chance this could be reworked to use a more declarative and intuitive router, like react-router? The switch statements in the Application component are kinda gross... :/

You could also have more declarative document titles with react-document-title, which also supports server-side rendering with a convenient rewind() method.

**Comment by mridgway** [comment]
Hi @benoneal,

I have started an example using react-router that you can see here: https://github.com/mridgway/flux-example/tree/react-router/routing

We plan on adding it as a separate example in the future.

**Comment by benoneal** [comment]
Thanks for that Michael. Am I correct though that the ApplicationStore and PageStore are now largely irrelevant? Like, most of their methods revolve around routing, and the ApplicationStore doesn't even have an action handler to match the navigate 'CHANGE_ROUTE' action, and the LOAD_PAGE action expected by the PageStore isn't triggered anywhere?

**Comment by mridgway** [comment]
Yeah, react-router doesn't use the Flux pattern, so the ApplicationStore and PageStore are not needed any more, nor are the actions called. You could still dispatch an action in react-routers callback if you wanted to so that other stores could listen for route changes though. In this example it didn't seem necessary though.

**Comment by redonkulus** [comment]
@benoneal the example is now available [here](https://github.com/yahoo/flux-examples/tree/master/react-router)
